# Google Cloud Build configuration for Media Procurement Platform

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/media-procurement-backend:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/media-procurement-backend:latest'
      - './backend'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/media-procurement-backend:$BUILD_ID'

  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/media-procurement-backend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'media-procurement-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/media-procurement-backend:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/media-procurement-backend:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/media-procurement-backend:latest'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Timeout for the entire build
timeout: '1200s'

