name: Proposaland Monitor Scheduler

on:
  schedule:
    - cron: '0 9 * * *' # Runs every day at 09:00 UTC
  workflow_dispatch:     # Allows manual trigger

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Proposaland Monitor
        run: python proposaland_monitor.py